affinity/slate

source/includes/_data-model.md, source/includes/_entity-attributes.md, source/includes/_entity-values.md, source/includes/_list-entries.md, source/includes/_lists.md, source/includes/_notes.md, source/includes/_organizations.md, source/includes/_persons.md
=> Entity Attributes -> Fields, Entity Values -> Field Values

source/includes/_entity-values.md, source/includes/_list-entries.md, source/includes/_lists.md, source/includes/_notes.md, source/includes/_organizations.md, source/includes/_persons.md, source/index.html.md
=> API token as HTTP header

source/includes/_organizations.md, source/includes/_persons.md
=> Add new documentation for paginated persons and organizations requests

source/includes/_list-entries.md, source/includes/_notes.md
=> Add documentation for specifying creator of a note or list entry in External API

source/includes/_data-model.md, source/includes/_entity-attributes.md, source/includes/_entity-values.md, source/includes/_list-entries.md, source/includes/_lists.md, source/includes/_notes.md, source/includes/_opps.md, source/includes/_organizations.md, source/includes/_persons.md, source/index.html.md
=> Add Opportunity doc to external api

source/includes/_organizations.md, source/includes/_persons.md
Documentation for PR: https://github.com/affinity-team/affinity/pull/3762.
=> Add first_email_date to interactions

source/includes/_entity-files.md, source/index.html.md
Documentation for https://github.com/affinity-team/affinity/pull/4362.
=> Support uploading entity files

source/includes/_organizations.md
Code PR: https://github.com/affinity-team/affinity/pull/4612
=> [Organizations] Expose Crunchbase UUID

source/includes/_notes.md
!!!!! STOP AND READ !!!!!
If the dropdown above says "base fork: lord/master", you are submitting your change to ALL USERS OF SLATE, not just your company. This is probably not what you want. Click "base fork" to change it to the right place.
If you're actually trying to submit a change to upstream Slate, please submit to our dev branch, PRs sent to the master branch are generally rejected.
=> Update notes documentation

source/includes/_entity-files.md
We also have an endpoint to download an entity file but it's not working. Once that's fixed, will have a separate PR for that.
=> Adds get all entity files and a specific entity file to documentation.

source/includes/_list-entries.md, source/includes/_persons.md
lol https://app.asana.com/0/572858660383888/1113920509763243/f
=> Remove phone numbers

source/includes/_entity-files.md, source/includes/_notes.md
Associated with https://github.com/affinity/affinity/pull/7778
per request of Zihao and Milbs
=> Allow filtering files by entity

source/index.html.md
=> Change API rate limit from 150k to 450k on the docs.

source/includes/_list-entries.md
Added documentation for GET endpoint for list entries to include pagination.
=> Update documentation for GET list entries.

source/includes/_webhooks.md
Added documentation for webhooks
=> Add documentation for webhooks

source/includes/_additional-materials.md, source/includes/_data-model.md, source/includes/_entity-attributes.md, source/includes/_entity-files.md, source/includes/_entity-values.md, source/includes/_list-entries.md, source/includes/_lists.md, source/includes/_notes.md, source/includes/_opps.md, source/includes/_organizations.md, source/includes/_persons.md, source/includes/_relationship-strengths.md, source/index.html.md
Just ran prettier on all of the *.md files in this directory
=> Run prettier on all *.md files

source/includes/_persons.md
https://app.asana.com/0/572858660383888/1162787954915393/f
Update API Docs to use correct persons endpoint.
=> update persons curl api url

source/includes/_additional-materials.md
Old url broke, updated python link to a working url.
=> Fix Python link.

source/includes/_entity-attributes.md
=> GET Fields

source/includes/_notes.md
Docs for DELETE /notes/:note_id
[Main PR change](https://github.com/affinity/affinity/pull/12590)
=> Add docs for Notes DELETE route.

source/includes/_notes.md, source/includes/_persons.md
Also made a small fix to a typo in a different section.
[Main PR](https://github.com/affinity/affinity/pull/12624)
=> Add docs for Notes PUT route.

source/includes/_entity-value-changes.md, source/index.html.md
[Actual Changes](https://github.com/affinity/affinity/pull/12670)
=> Add field value changes docs.

source/includes/_entity-value-changes.md
=> Update field value changes copy.

source/includes/_opps.md
Fix Opps documentation. Updated the fields to what we actually return in the response, and snake-cased the keys.
=> Fix Opps documentation.

source/includes/_entity-files.md
Update docs to snake case entity file fields. Not including camel cased fields since we want new customers to use snake cased fields.
=> Snake case entity file fields.

source/index.html.md
Quick change.
[Asana Task](https://app.asana.com/0/1136831502334327/1185945479062599)
=> Update rate limit.

source/includes/_entity-attributes.md, source/includes/_entity-values.md
Add the DELETE `Field` endpoint to the api docs.
=> Surface delete Field endpoint.

source/includes/_lists.md
Lists support Opps, and our docs should reflect that.
=> Add opp type for lists to the doc.

source/includes/_entity-value-changes.md
The values for `UPDATED` and `DELETED` were flipped. This PR sets them to the correct values.
=> Fix entity value change action types.

source/includes/_organizations.md, source/includes/_persons.md
https://app.asana.com/0/1176772761628309/1188107199072320/f
=> Update API docs so that first_event is included, and persons associated with interactions.

source/includes/_organizations.md, source/includes/_persons.md
Since returning persons with every interaction slows and causes timeouts.
https://app.asana.com/0/572858660383888/1193437840209227/f
=> Update api docs to show new parameter `with_interaction_persons`

source/includes/_persons.md
I used a newline instead of letting word wrap take care of the table.
=> Fix table formatting.

source/includes/_entity-attributes.md, source/includes/_entity-value-changes.md
Clarified language for field types and added info on which field types support tracking changes
Useful slab doc - https://affinity.slab.com/posts/a-guide-to-column-field-entity-attribute-value-types-bcjjcf1e#naming-issues-dropdowns-text
=> Field types that support field value changes

source/includes/_webhooks.md
For https://app.asana.com/0/1195690886594321/1200031721293186/f
=> Update doc that enrichment webhooks are not included.

source/index.html.md
**Asana Task**:  https://app.asana.com/0/1199933461955492/1200318488608944/f
Update the API rate limit information. We don't want to provide the exact API limit details in the docs for now. Updated the text as per the decision made in the associated Asana task.
=> update api rate limit
